name: SarSys
description: SarSys

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.1+86

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  flutter_appauth: ^0.9.2+2
  flutter_secure_storage: ^4.1.0
  jose: ^0.2.1+1
  sqflite: ^1.1.5
  shared_preferences: ^0.5.2
  geolocator: ^5.0.0
  geocoder: ^0.2.1
  flutter_launcher_icons: ^0.8.1
  uni_links: ^0.4.0
  http: ^0.12.0+2
  path: ^1.6.2
  path_provider: ^1.1.0
  protobuf: ^1.0.1
  web_socket_channel: ^1.2.0
  rxdart: ^0.23.0
  json_annotation: ^3.0.1
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^2.0.0
  jaguar_jwt: ^2.1.6
  flutter_form_builder: ^4.2.0
  flutter_chips_input: ^1.3.1
  app_settings: ^4.0.2
  permission_handler: ^5.0.1+1
  flutter_slidable: ^0.5.3
  package_info: ^0.4.0+5
  font_awesome_flutter: ^9.0.0
  flutter_map: ^0.11.0
  badges: ^1.1.0
  sentry: ^3.0.0+1
  catcher: ^0.3.23
  device_info: ^1.0.0
  url_launcher: ^6.0.2
  material_design_icons_flutter: ^4.0.5345
  filesize: ^1.0.4
  dartz: ^0.9.1
  intro_views_flutter: ^2.8.1
  flutter_email_sender: ^3.0.1
  provider: ^4.3.3
  wakelock: ^0.5.0+2
  faker: ^1.1.1
  connectivity: ^3.0.3
  data_connection_checker: ^0.3.4
  xml: ^4.2.0
  pin_code_fields: ^2.4.0
  local_auth: ^0.6.1+3
  hive: ^1.4.4+1
  hive_flutter: ^0.3.0+2
  flutter_udid: ^1.0.1
  simple_gravatar: ^1.0.5
  json_patch: ^2.0.0
  cached_network_image: ^2.3.1
  flutter_cache_manager: ^1.4.1
  flutter_phoenix: ^1.0.0
  chopper: ^3.0.2
  debounce_throttle: ^2.0.0
  grouped_list: ^3.3.0
  flutter_background_geolocation: 2.0.0
  percent_indicator: ^2.1.5
  timer_builder: ^1.3.0
  keyboard_avoider: ^0.1.2

  # Mocking support
  uuid: ^2.0.2
  random_string: ^2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dependency_overrides:
  intl: ^0.17.0
  country_pickers: 2.0.0
#  flutter_map:
#    # Use local branch of flutter_map
#    path: ../flutter_map
  flutter_map:
    # Use local branch of flutter_map
    #path: ../flutter_map
    git:
      url: git://github.com/fleaflet/flutter_map
      ref: master
      # Merged PR https://github.com/johnpryan/flutter_map/pull/577 Evict error tiles
      # Merged PR https://github.com/johnpryan/flutter_map/pull/584 Observe TileLayerOptions changes
      # Proposed fix for missing disposal of AnimationController in Tile class
#      url: https://github.com/DISCOOS/flutter_map
#      ref: track_change_and_evict_errors
#      ref: issues/836

#  intro_views_flutter:
#    #path: ../IntroViews-Flutter
#    git:
#      url: https://github.com/aagarwal1012/IntroViews-Flutter.git
#      ref: master

#  flutter_chips_input:
#    path: ../flutter_chips_input
#    git:
#      url: https://github.com/danvick/flutter_chips_input.git
#      ref: master

  pin_code_fields:
    #path: ../pin_code_fields
    git:
      url: https://github.com/DISCOOS/pin_code_fields.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  bloc_test: ^4.0.0
  build_runner: ^1.10.0
  json_serializable: ^3.2.5
  chopper_generator: ^3.0.4

flutter_icons:
  android: true #"launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  image_path_android: "assets/icon_android.png"
  #image_path_ios: "assets/images/icon-710x599-ios.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - logo.png
    - assets/config/base_map.json
    - assets/config/fleet_map.json
    - assets/config/app_config.json
    - assets/images/map.png
    - assets/pending_tile.png
    - assets/error_tile.png
    - assets/offline_tile.png
    - assets/images/cabin.png
    - assets/images/sar-team-2.png
    - assets/images/avatar-male.png
    - assets/images/google.png
    - assets/images/download.png
    - assets/mapspreview/missing.png
    - assets/mapspreview/topo4.png
    - assets/mapspreview/normaphd.png
    - assets/mapspreview/toporaster3.png
    - assets/mapspreview/ortofoto.png
    - assets/mapspreview/hybrid.png
    - assets/mapspreview/sjokart.png
    - assets/mapspreview/osm.png
    - assets/mapspreview/mapant.png

  fonts:
    - family: SarSysIcons
      fonts:
        - asset: assets/icons/SarSys.ttf
    - family: PTMono
      fonts:
        - asset: assets/fonts/PTMono-Bold.ttf
