name: SarSys
description: SarSys

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.1+78

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  flutter_appauth: ^0.8.1
  flutter_secure_storage: ^3.2.1+1
  jose: ^0.1.2
  sqflite: ^1.1.5
  shared_preferences: ^0.5.2
  geolocator: ^5.0.0
  geocoder: ^0.2.1
  flutter_launcher_icons: ^0.7.0
  uni_links: ^0.2.0
  http: ^0.12.0+2
  path: ^1.6.2
  path_provider: ^1.1.0
  protobuf: ^0.13.11
  web_socket_channel: ^1.0.12
  rxdart: ^0.22.0
  json_annotation: ^3.0.1
  bloc: ^0.13.0
  flutter_bloc: ^0.13.0
  equatable: ^0.2.3
  jaguar_jwt: ^2.1.6
  flutter_form_builder: ^3.5.4
  flutter_chips_input: ^1.3.1
  app_settings: 3.0.1
  permission_handler: ^3.1.0
  flutter_slidable: ^0.5.3
  package_info: ^0.4.0+5
  font_awesome_flutter: ^8.5.0
  flutter_map: ^0.7.5
  badges: ^1.1.0
  sentry: ^2.2.0
  catcher: ^0.2.4
  device_info: ^0.4.0+2
  url_launcher: ^5.1.2
  material_design_icons_flutter: ^3.2.3895
  filesize: ^1.0.4
  dartz: ^0.8.7
  intro_views_flutter: ^2.6.0
  flutter_email_sender: ^2.0.3
  provider: ^3.1.0
  wakelock: ^0.1.4
  faker: ^1.1.1
  connectivity: ^0.4.8+2
  data_connection_checker: ^0.3.4
  xml: ^3.5.0
  pin_code_fields: ^2.4.0
  local_auth: ^0.6.1+3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  flutter_udid: ^1.0.1
  simple_gravatar: ^1.0.5

  # Mocking support
  uuid: ^2.0.2
  random_string: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dependency_overrides:
  flutter_map:
    # Use local branch of flutter_map
    #path: ../flutter_map
    git:
    #  url: git://github.com/johnpryan/flutter_map
      url: https://github.com/DISCOOS/flutter_map
      ref: master

  intro_views_flutter:
    #path: ../IntroViews-Flutter
    git:
      url: https://github.com/aagarwal1012/IntroViews-Flutter.git
      ref: master
  flutter_chips_input:
    #path: ../flutter_chips_input
    git:
      url: https://github.com/danvick/flutter_chips_input.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  build_runner: ^1.8.0
  json_serializable: ^3.2.5

flutter_icons:
  android: true #"launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  image_path_android: "assets/icon_android.png"
  #image_path_ios: "assets/images/icon-710x599-ios.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - logo.png
    - assets/config/base_map.json
    - assets/config/fleet_map.json
    - assets/config/app_config.json
    - assets/images/map.png
    - assets/pending_tile.png
    - assets/error_tile.png
    - assets/offline_tile.png
    - assets/images/cabin.png
    - assets/images/sar-team-2.png
    - assets/images/avatar-male.png
    - assets/images/google.png
    - assets/mapspreview/missing.png
    - assets/mapspreview/topo4.png
    - assets/mapspreview/normaphd.png
    - assets/mapspreview/toporaster3.png
    - assets/mapspreview/ortofoto.png
    - assets/mapspreview/hybrid.png
    - assets/mapspreview/sjokart.png
    - assets/mapspreview/osm.png

  fonts:
    - family: SarSysIcons
      fonts:
        - asset: assets/icons/SarSys.ttf
