name: SarSys
description: SarSys

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.1+26

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  flutter_secure_storage: ^3.2.1+1
  jose: ^0.1.2
  sqflite: ^1.1.5
  shared_preferences: ^0.5.2
  geolocator: ^5.0.0
  flutter_launcher_icons: ^0.7.0
  uni_links: ^0.2.0
  http: ^0.12.0+2
  path: ^1.6.2
  path_provider: ^1.1.0
  protobuf: ^0.13.11
  web_socket_channel: ^1.0.12
  rxdart: ^0.22.0
  json_annotation: ^2.0.0
  bloc: ^0.13.0
  flutter_bloc: ^0.13.0
  equatable: ^0.2.3
  jaguar_jwt: ^2.1.6
  flutter_form_builder: ^3.5.3
  flutter_chips_input: ^1.3.1
  system_setting: ^0.1.3
  permission_handler: ^3.1.0
  flutter_slidable: ^0.5.3
  package_info: ^0.4.0+5
  font_awesome_flutter: ^8.5.0
  badges: ^1.1.0
  sentry: ^2.2.0
  catcher: ^0.2.0
  device_info: ^0.4.0+2
  url_launcher: ^5.1.2
  material_design_icons_flutter: ^3.2.3895
  filesize: ^1.0.4
  dartz: ^0.8.7
  intro_views_flutter: ^2.6.0
  flutter_email_sender: ^2.0.3

  # Customized plugins
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map
      ref: master

  # Mocking support
  uuid: ^2.0.2
  random_string: ^0.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dependency_overrides:
  # Fixes version mismatch on intl between flutter_form_builder and  flutter_localizations from sdk
  # Fix in PR https://github.com/danvick/flutter_form_builder/pull/1xx
  flutter_form_builder:
    path: ../flutter_form_builder/


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter_icons:
  android: true #"launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  image_path_android: "assets/icon_android.png"
  #image_path_ios: "assets/images/icon-710x599-ios.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - logo.png
    - assets/config/app_config.json
    - assets/config/fleet_map.json
    - assets/images/map.png
    - assets/images/cabin.png
    - assets/images/sar-team 2.png
    - assets/images/avatar male.png
    - assets/mapspreview/missing.png
    - assets/mapspreview/topo4.png
    - assets/mapspreview/toporaster3.png
    - assets/mapspreview/ortofoto.png
    - assets/mapspreview/hybrid.png
    - assets/mapspreview/sjokart.png


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
